### ISSUE TITLE
License

### ISSUE THREAD

**Issue by XakepSDK** [dawidgora/keycloak-unique-attribute-validator-provider#1]
Could you please choose a license for the project? MIT, LGPL, or other
Otherwise people can't use your code

**Comment by dawidgora** [comment]
Hey, sure, I'll handle it as soon as I find some time in the following days.

**Comment by dawidgora** [comment]
Ok, actually, I found some time already and have added a LICENSE to the repo. 

Thank you for reaching out to me.
