### ISSUE TITLE
Does it work in Keycloak 23.0.1?

### ISSUE THREAD

**Issue by PixStudioPL** [dawidgora/keycloak-unique-attribute-validator-provider#2]
Does it work in Keycloak 23.0.1? I can't see a validator in my keycloak. I have all settings like in your realm.
I have other functionality I wrote but can't see this extra validator during user field edit.

admin/master/console/#/master/providers
on validators list is also not visible

**Comment by dawidgora** [comment]
Hey, I will try to find some time this week and check.

**Comment by dawidgora** [comment]
@PixStudioPL I've checked the code on Keycloak 23.0.1, and I can confirm that it is working. Can you share more information about your config? Is your `jar` file in `/opt/keycloak/providers`?

**Comment by PixStudioPL** [comment]
Hi Dawid. Thanks for message. I have in docker file 
COPY plugin.jar /opt/keycloak/providers/
and other plugins as well in this jar and they are working, your is not appearing in admin when edit user attribute in
Choose Realm -> Realm Settings -> User profile -> Any attribute (phoneNumber for example) -> Add validator -> no yours validator. Do I did something wrong?

**Comment by PixStudioPL** [comment]
If you go to admin/master/console/#/master/providers can you see under validators your validator?

**Comment by dawidgora** [comment]
Yes, I can see it there, as you can see on the attached screenshot. 

![CleanShot 2024-05-10 at 13 45 39@2x](https://github.com/dawidgora/keycloak-unique-attribute-validator-provider/assets/108656216/d7216257-fad6-42de-831b-e59c397e8bd5)

Can you check logs from the Docker container? Maybe there is some error related to loading the validator.

If you won't be able to fix it, I can release the jar, here on github.

**Comment by PixStudioPL** [comment]
Thanks a lot. I do not have it. I have to check docker probably ... thank you very much for your time

**Comment by dawidgora** [comment]
You can copy logs from the Docker container of your Keycloak here, and I can help you debug.

**Comment by PixStudioPL** [comment]
Thanks a lot. My fault. I'm C# programmer. I forgot to copy as well meta resources files. It is working now. Sorry for wasting your time. I was trying to use ValidationError third parameter as message key for localization for Polish and English language. But without luck. My attribute is "mobilePhone" as a language key I set "error.duplicated.attribute.mobilePhone" but red error in form is always "mobilePhone" not message. Any ideas ;) It is working in registration form not in admin panel?

**Comment by linus-ha** [comment]
This issue can be closed, I think.
I can report: This validator works in Keyclaok v25.0.1.
Thanks a lot for your work!
